### ISSUE TITLE
function time_us() returns unexpected result

### ISSUE THREAD

**Issue by ghost** [ekondayan/micropython-ntp#2]
I don't know if there are different implementations that work fine, but in my case I have problems with time_us() and all the other functions depending on it.
the source of mktime uses this order of arguments:
```
mp_uint_t timeutils_mktime_2000(mp_uint_t year, mp_int_t month, mp_int_t mday,
    mp_int_t hours, mp_int_t minutes, mp_int_t seconds)
```
but if we use RTC.datetime as callback, it returns (year, month, day, weekday, hours, minutes, seconds, subseconds).
The order is different, therefore the suggested patch. #3

**Comment by ekondayan** [comment]
Thank you for pointing that out. 
The root of this bug comes from the fact that  micropython has two functions: time.localtime() and RTC.datetime(); that do the same thing but take slightly different parameter, which was always very frustrating for me. In commit `5f73fab068867d7fc21d8b71ab93279887ad5a1f`, I decided to make the two functions `time()` and `datetime()` accept exactly the same input parameter, contrary to the micropython's approach.

At that time it seemed as a good idea, but now I see it is a source of confusion and errors. Due to this, a similar bug is also present in the function `dst()`.

Currently I am working on that and will push a commit addressing this inconsistency.

**Comment by ekondayan** [comment]
This issue is fixed in the latest commit.

Thank you.
